apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stashapp-config
  labels:
    tier: stashapp-config
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/AppConfig/StashApp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-whisparr-config
  labels:
    tier: whisparr-config
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/AppConfig/Whisparr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dirt-data
  labels:
    tier: dirt-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Dirt/Content
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stashapp-metadata
  labels:
    tier: stashapp-metadata
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Dirt/Stash/metadata
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stashapp-cache
  labels:
    tier: stashapp-cache
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Dirt/Stash/cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stashapp-blob
  labels:
    tier: stashapp-blobs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Dirt/Stash/blobs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-stashapp-generated
  labels:
    tier: stashapp-generated
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Dirt/Stash/generated