apiVersion: v1
kind: Namespace
metadata:
  name: media-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-movies
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Movies   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-movies  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-downloads
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Downloads/Complete   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-downloads  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-incomplete
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Downloads/Incomplete   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incomplete-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-incomplete  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tv
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/TV   
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-music
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Music   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-music  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-books
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Books   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-books  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-learn
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Learn   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: learn-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-learn  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-config
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/AppConfig 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-config  
  storageClassName: ""      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tv
  namespace: media-server 
spec:
  capacity:
    storage: 100Gi        
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:           
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.11.11.46
    path: /mnt/data/TV 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-pvc
  namespace: media-server 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi         
  volumeName: nfs-pv-tv  
  storageClassName: ""      
---



