apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-server   
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/radarr:latest
        ports:
        - containerPort: 7878
        env:
        - name: PUID
          value: "1000" # Replace with your user ID
        - name: PGID
          value: "1000" # Replace with your group ID
        - name: TZ
          value: "America/Chicago" # Replace with your timezone
        volumeMounts:
        - name: nfs-pv-config
          mountPath: /config/radarr
        - name: nfs-pv-movies
          mountPath: /Movies
        - name: nfs-pv-downloads
          mountPath: /downloads
      volumes:
       - name: nfs-pv-config
         persistentVolumeClaim:
          claimName: config-pvc      
       - name: nfs-pv-movies
         persistentVolumeClaim:
          claimName: nfs-pv-movies
      -  name: nfs-pv-downloads
         persistentVolumeClaim:
           claimName: nfs-pv-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
  type: ClusterIP # Or NodePort/LoadBalancer for external access