apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-config
  labels:
    app: sabnzbd
    tier: config
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/AppConfig/Sabnzbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: sabnzbd
      tier: config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-downloads
  labels:
    app: sabnzbd
    tier: media
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Downloads/Complete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: sabnzbd
      tier: media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sabnzbd-incomplete
  labels:
    app: sabnzbd
    tier: media
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: 10.11.11.46
    path: /mnt/data/Downloads/Incomplete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sabnzbd-incomplete
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: sabnzbd
      tier: media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      # Helps NFS permissions
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config              # Plex expects config here
            - name: downloads
              mountPath: /Downloads/Complete
            - name: incomplete
              mountPath: /Downloads/Incomplete
          # If you also want library mounts later, add more volumeMounts here.
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20      
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-sabnzbd-config
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-sabnzbd-downloads
        - name: incomplete
          persistentVolumeClaim:
            claimName: pvc-sabnzbd-incomplete
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.11.11.83    # pick a free IP in your MetalLB range
  selector:
    app: sabnzbd
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
