apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr  
  namespace: media-server   
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: "1000" # Replace with your user ID
        - name: PGID
          value: "1000" # Replace with your group ID
        - name: TZ
          value: "America/New_York" # Replace with your timezone
        volumeMounts:
          - name: nfs-pv-config
            mountPath: /config/sonarr
          - name: nfs-pv-tv
            mountPath: /data/TV 
        #- name: downloads
        #  mountPath: /data/downloads # Adjust as per your download client setup
      volumes:
      - name: nfs-pv-config
        persistentVolumeClaim:
          claimName: sonarr-config-pvc # Name of your PVC for Sonarr config
      - name: nfs-pv-tv
        persistentVolumeClaim:
          claimName: media-pvc # Name of your PVC for media library
      - name: nfs-pv-downloads
        persistentVolumeClaim:
          claimName: downloads-pvc # Name of your PVC for downloads
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP # Or NodePort/LoadBalancer