apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-music
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      tier: music
---