apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stashapp-config
  namespace: dirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
     tier: stashapp-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dirt-data
  namespace: dirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      tier: dirt-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stashapp-metadata
  namespace: dirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      tier: stashapp-metadata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stashapp-cache
  namespace: dirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      tier: stashapp-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stashapp-blobs
  namespace: dirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
         tier: stashapp-blobs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stashapp-generated
  namespace: dirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      tier: stashapp-generated
---