apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      # Helps NFS permissions
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config              # Plex expects config here
            - name: tv
              mountPath: /TV
            - name: movies
              mountPath: /Movies

          # If you also want library mounts later, add more volumeMounts here.
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-bazarr-config
        - name: tv
          persistentVolumeClaim:
            claimName: pvc-tv
        - name: movies
          persistentVolumeClaim:
            claimName: pvc-movies

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.11.11.86    # pick a free IP in your MetalLB range
  selector:
    app: bazarr
  ports:
    - name: http
      port: 6767
      targetPort: 6767
      protocol: TCP
