---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      # Helps NFS permissions
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config              # Plex expects config here
            - name: music
              mountPath: /Music
            - name: downloads
              mountPath: /Downloads/Complete
            - name: incomplete
              mountPath: /Downloads/Incomplete
          # If you also want library mounts later, add more volumeMounts here.
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-lidarr-config
        - name: music
          persistentVolumeClaim:
            claimName: pvc-music
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: incomplete
          persistentVolumeClaim:
            claimName: pvc-download-incomplete
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.11.11.84    # pick a free IP in your MetalLB range
  selector:
    app: lidarr
  ports:
    - name: http
      port: 8686
      targetPort: 8686
      protocol: TCP
