apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      # Helps NFS permissions
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config              # Plex expects config here
            - name: movies
              mountPath: /Movies
            - name: downloads
              mountPath: /Downloads/Complete
            - name: incomplete
              mountPath: /Downloads/Incomplete
          # If you also want library mounts later, add more volumeMounts here.
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-radarr-config
        - name: movies
          persistentVolumeClaim:
            claimName: pvc-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: incomplete
          persistentVolumeClaim:
            claimName: pvc-download-incomplete
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.11.11.84    # pick a free IP in your MetalLB range
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      targetPort: 7878
      protocol: TCP
